name: Semantic Release
run-name: Semantic Release by ${{ github.actor }}
on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PNPM environment
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install deps
        run: rm -rf node_modules && pnpm install
      - name: Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
